In [1]:
import numpy as np
from numpy.random import MT19937
from numpy.random import RandomState, SeedSequence


vec = np.arange(0,15)
print(vec,"\n")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 



In [2]:
# array range with 2nd parameter exclusive and steps  up by 3rd parameter
vec1 = np.arange(0, 25, 3)
print(vec1,"\n")


[ 0  3  6  9 12 15 18 21 24] 



In [3]:

# Linear space, with first two parameters both inclusive and 
# that range is divided into equal parts denoted by 3rd parameter 
vec2 = np.linspace(0,4.5,12)
print(vec2)


[0.         0.40909091 0.81818182 1.22727273 1.63636364 2.04545455
 2.45454545 2.86363636 3.27272727 3.68181818 4.09090909 4.5       ]


In [4]:
# Resizes the array into a matrix
mat1 = vec2.reshape(3,4)
print(mat1)

[[0.         0.40909091 0.81818182 1.22727273]
 [1.63636364 2.04545455 2.45454545 2.86363636]
 [3.27272727 3.68181818 4.09090909 4.5       ]]


In [6]:

mat2 = np.ones((3,4))
print(mat2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:

mat3 = np.ones((1,5))
print(mat3)


[[1. 1. 1. 1. 1.]]


In [10]:
# identity matrix
mat4 = np.ones((4,3))
print(mat4)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:

print(mat1**mat2)



[[0.         0.40909091 0.81818182 1.22727273]
 [1.63636364 2.04545455 2.45454545 2.86363636]
 [3.27272727 3.68181818 4.09090909 4.5       ]]


In [12]:
mat_product = np.matmul(mat4,mat1)
print (mat_product,"\n")


[[4.90909091 6.13636364 7.36363636 8.59090909]
 [4.90909091 6.13636364 7.36363636 8.59090909]
 [4.90909091 6.13636364 7.36363636 8.59090909]
 [4.90909091 6.13636364 7.36363636 8.59090909]] 



In [13]:

# Need to investigate more on how linalg.solve works
# print(np.linalg.solve(mat4, mat_product))

# generates uniform random 3x4 matrix with values between 0 and 1 
rmat1 = np.random.rand(3,4)
print(rmat1,"\n")

# generates standard normal random 3x4 matrix with any fractional value 
rmat2 = np.random.randn(3,4)
print(rmat2,"\n")

print(np.mean(rmat1),"\n")
print(np.mean(rmat2),"\n")

print(np.std(rmat1),"\n")
print(np.std(rmat2),"\n")

print(np.max(rmat1),"\n")
print(np.max(rmat2),"\n")

print(np.min(rmat1),"\n")
print(np.min(rmat2),"\n")


[[0.76099716 0.48371562 0.51310333 0.02258362]
 [0.44053667 0.03442488 0.64402157 0.64113593]
 [0.81801508 0.10073687 0.39583816 0.77238807]] 

[[-0.31831943 -0.60811259 -0.57201539  1.03038454]
 [-0.87092758  0.77282786 -0.29330989  1.13503586]
 [-1.02938556 -0.49906171  2.70806264 -0.50088402]] 

0.4689580801333408 

0.0795245604578089 

0.2725599044825125 

1.0570175158414434 

0.818015078732271 

2.7080626395245067 

0.022583622598756348 

-1.029385562518218 



In [14]:

rvec1 = np.random.rand(15)
print(rvec1,"\n")

print(rvec1[0:5],"\n")
print(rvec1[np.arange(0,5)],"\n")

print(rvec1[3:11],"\n")
print(rvec1[np.arange(3,11)],"\n")

print(np.arange(0,15,3))
print(rvec1[np.arange(0,15,3)],"\n")

rmat3 = np.random.randn(6,5)
print(rmat3,"\n")

print(rmat3[0:3,2:4],"\n")
rmat3[0:3,2:4] = 1
print(rmat3,"\n")

print(rmat3==1,"\n")
rmat3[rmat3==1] = 0.5
print(rmat3,"\n")



[0.7195135  0.17643963 0.16383592 0.96984898 0.71361854 0.03843145
 0.99682183 0.68232092 0.41940047 0.02582616 0.89567707 0.33646762
 0.22190102 0.30620727 0.46743458] 

[0.7195135  0.17643963 0.16383592 0.96984898 0.71361854] 

[0.7195135  0.17643963 0.16383592 0.96984898 0.71361854] 

[0.96984898 0.71361854 0.03843145 0.99682183 0.68232092 0.41940047
 0.02582616 0.89567707] 

[0.96984898 0.71361854 0.03843145 0.99682183 0.68232092 0.41940047
 0.02582616 0.89567707] 

[ 0  3  6  9 12]
[0.7195135  0.96984898 0.99682183 0.02582616 0.22190102] 

[[ 0.23823856  1.91051796  0.05837659 -0.69313231 -0.64989626]
 [ 1.32874515 -1.15697232 -0.98885347 -1.18894865  1.25826077]
 [-0.76911958 -0.60238673  0.78020625 -0.97244733  0.4456807 ]
 [ 0.27560372 -0.50552222  0.67122165 -0.2068596   0.54585032]
 [ 0.74770231 -0.36833329  0.30086338  0.84482791  1.17004732]
 [ 0.61361425 -1.49739457  0.40934112  1.27730527 -0.14564154]] 

[[ 0.05837659 -0.69313231]
 [-0.98885347 -1.18894865]
 [ 0.78020625 

In [15]:
# Need to find how to combine two or more logical operators in assigning values e.g. rmat3[0.5<= rmat3 <= 1.0] = 0.5
rmat3[0.5<rmat3 ] = -0.25
print(rmat3,"\n")


rs = np.random.RandomState(MT19937(SeedSequence(123)))
rmat4 = np.random.rand(100,150)
rmat5 = np.random.rand(125,100)

print(rmat4,"\n")
print(rmat5,"\n")


[[ 0.23823856 -0.25        0.5         0.5        -0.64989626]
 [-0.25       -1.15697232  0.5         0.5        -0.25      ]
 [-0.76911958 -0.60238673  0.5         0.5         0.4456807 ]
 [ 0.27560372 -0.50552222 -0.25       -0.2068596  -0.25      ]
 [-0.25       -0.36833329  0.30086338 -0.25       -0.25      ]
 [-0.25       -1.49739457  0.40934112 -0.25       -0.14564154]] 

[[0.5609664  0.14584399 0.57570966 ... 0.87665331 0.67635507 0.60770396]
 [0.77579299 0.92150334 0.13784073 ... 0.18752979 0.06821768 0.05154725]
 [0.84539205 0.36035844 0.13916713 ... 0.89844339 0.04665828 0.15592671]
 ...
 [0.76761948 0.69403402 0.30091839 ... 0.74816624 0.94856196 0.91373653]
 [0.30992272 0.574254   0.56257574 ... 0.83016806 0.53452852 0.17714111]
 [0.47251139 0.45485895 0.46053113 ... 0.19318133 0.16758679 0.94930581]] 

[[0.90740369 0.29696626 0.1685908  ... 0.90246598 0.83844047 0.89384702]
 [0.25534808 0.17155548 0.02763896 ... 0.96416176 0.31781438 0.43146591]
 [0.11721184 0.97606444 0.6

In [16]:

np.save("random_Array_File1",rmat4)
np.savez("random_Array_Filez",rmat4_array_file=rmat4,rmat5_array_file=rmat5)

ld_mat1 = np.load("random_Array_File1.npy")
print(ld_mat1,"\n")
ld_matzip = np.load("random_Array_Filez.npz")
print(ld_matzip,"\n")
ld_mat2 = ld_matzip['rmat4_array_file']
print(ld_mat2,"\n")
ld_mat3 = ld_matzip['rmat5_array_file']
print(ld_mat3,"\n")


[[0.5609664  0.14584399 0.57570966 ... 0.87665331 0.67635507 0.60770396]
 [0.77579299 0.92150334 0.13784073 ... 0.18752979 0.06821768 0.05154725]
 [0.84539205 0.36035844 0.13916713 ... 0.89844339 0.04665828 0.15592671]
 ...
 [0.76761948 0.69403402 0.30091839 ... 0.74816624 0.94856196 0.91373653]
 [0.30992272 0.574254   0.56257574 ... 0.83016806 0.53452852 0.17714111]
 [0.47251139 0.45485895 0.46053113 ... 0.19318133 0.16758679 0.94930581]] 


[[0.5609664  0.14584399 0.57570966 ... 0.87665331 0.67635507 0.60770396]
 [0.77579299 0.92150334 0.13784073 ... 0.18752979 0.06821768 0.05154725]
 [0.84539205 0.36035844 0.13916713 ... 0.89844339 0.04665828 0.15592671]
 ...
 [0.76761948 0.69403402 0.30091839 ... 0.74816624 0.94856196 0.91373653]
 [0.30992272 0.574254   0.56257574 ... 0.83016806 0.53452852 0.17714111]
 [0.47251139 0.45485895 0.46053113 ... 0.19318133 0.16758679 0.94930581]] 

[[0.90740369 0.29696626 0.1685908  ... 0.90246598 0.83844047 0.89384702]
 [0.25534808 0.17155548 0.02763896

In [17]:

np.savetxt("random_Array_File1.csv",rmat4,delimiter=',')

ld_mat1 = np.loadtxt("random_Array_File1.csv",delimiter=',')
print(ld_mat1,"\n")

# Only numbers can be processed with NumPy
# ld_drill_raw = np.loadtxt("drill.csv",delimiter=",")
# print(ld_drill_raw,"\n")


[[0.5609664  0.14584399 0.57570966 ... 0.87665331 0.67635507 0.60770396]
 [0.77579299 0.92150334 0.13784073 ... 0.18752979 0.06821768 0.05154725]
 [0.84539205 0.36035844 0.13916713 ... 0.89844339 0.04665828 0.15592671]
 ...
 [0.76761948 0.69403402 0.30091839 ... 0.74816624 0.94856196 0.91373653]
 [0.30992272 0.574254   0.56257574 ... 0.83016806 0.53452852 0.17714111]
 [0.47251139 0.45485895 0.46053113 ... 0.19318133 0.16758679 0.94930581]] 



In [23]:
n = np.ones(4, dtype=np.int8)
n

array([1, 1, 1, 1], dtype=int8)